import React from 'react';
import config from '../config';
import './SummaryPage.scss';
import { kebabCase } from 'lodash';


export default props => {
  console.log('SummaryPage.render', props);

  let hazardUnits = [];
  Object.values(props.groupToHazardMap).forEach(hazardCodes => {
    hazardCodes.forEach(code => {
      hazardUnits = hazardUnits.concat(props.hazardToUnitMap[code]);
    })
  });

  return (
    <div className="page-break summary-page">
      <div className="header">
        <h1>Report Summary</h1>
      </div>
      <p dangerouslySetInnerHTML={{ __html: props.Top }} title={config.notProd && "ReportTextTable.Text(Top)"}></p>
      <p dangerouslySetInnerHTML={{ __html: props['Table1headingautogenerated table'] }}
        title={config.notProd && "ReportTextTable.Text(Table 1 heading...)"}></p>
      <table className="summary-page__table summary-page__table--bordered">
        <thead>
          <tr>
            <th>Mapped Geologic Hazards</th>
            <th>Mapped Hazard Susceptibility</th>
          </tr>
        </thead>
        <tbody>
          { hazardUnits.map((unit, index) =>
            <tr key={index}>
              <td><a href={`#${kebabCase(unit.HazardName)}`}>{unit.HazardName}</a></td>
              <td>{unit.UnitName}</td>
            </tr>
          )}
        </tbody>
      </table>
      {/* <p dangerouslySetInnerHTML={{ __html: props['Table2headingautogenerated table'] }}
        title={config.notProd && "ReportTextTable.Text(Table 2 heading...)"}></p> */}
      {/* <table className="summary-page__table summary-page__table--bordered">
        <thead>
          <tr>
            <th>Other Available Data</th>
          </tr>
        </thead> */}
        {/* <tbody>
          { props.lidarFeatures.length > 0 &&
            <tr>
              <td><a href="#lidar">Lidar Elevation Data (high-resolution ground topography)</a></td>
            </tr>
          }
          { props.aerialFeatures.length > 0 &&
            <tr>
              <td><a href="#aerial-photography">Aerial Photography and Imagery</a></td>
            </tr>
          }
          { props.aerialFeatures.length < 1 && props.lidarFeatures.length < 1 &&
            <tr>
              <td>No other data</td>
            </tr>
          }
        </tbody> */}
      {/* </table> */}
      <p dangerouslySetInnerHTML={{ __html: props.Bottom }} title={config.notProd && "ReportTextTable.Text(Bottom)"}></p>
    </div>
  );
};
